menu:
  主页: /
  所有文章: /archives

excerpt_link: 阅读全文
archive_yearly: false

widgets:
  - category
  - tag
  - tagcloud
  - recent_posts
  - blogroll

blogrolls:
  - iDom: http://www.idom.me
  - featherj: http://featherj.org
  - A闪: http://ashan.org
  - xsstomy: http://xsstomy.com

fancybox: true

duoshuo_shortname: xzper

google_analytics:
rss:
